### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by FXY0117** [nie-lang/UnsupervisedDeepImageStitching#11]
when I train your model, it always occurs this question, and I don know how to solve it.
Traceback (most recent call last):
  File "inference.py", line 109, in <module>
    inference_func(snapshot_dir)
  File "inference.py", line 65, in inference_func
    input_clip = np.expand_dims(data_loader.get_data_clips(i, 128, 128), axis=0)
  File "D:\mmdetection\UnsupervisedDeepImageStitching-main\ImageAlignment\Codes\utils.py", line 86, in get_data_clips
    image = np_load_frame(data_info_list[i]['frame'][index], resize_height, resize_width)
IndexError: list index out of range
Is it because of my data error?

**Comment by nie-lang** [comment]
Well, in windows OS, you may have to modify the codes in line 71 of ImageAlignment/Codes/utils.py from
```
data_name = data.split('/')[-1]
```
to
```
data_name = data.split('\\')[-1]
```

So does the reconstruction module.

**Comment by FXY0117** [comment]
Excuse me, would you mind introducing the differences of the following  image-alignment pretrained models:
model.ckpt-1000000.data-00000-of-00001
model.ckpt-1000000.index
model.ckpt-1000000.meta
I just don't know choose which one to test

**Comment by FXY0117** [comment]
Excuse me ,when I run the inference.py to calculate the PSNR and SSIM, it occurs one question that I can't find the solution.
Traceback (most recent call last):
  File "inference.py", line 109, in <module>
    inference_func(snapshot_dir)
  File "inference.py", line 80, in inference_func
    psnr = skimage.measure.compare_psnr(input1*warp_one, warp*warp_one, 255)
AttributeError: module 'skimage' has no attribute 'measure'
Would you give me some advices?

**Comment by nie-lang** [comment]
One model (e.g. the pre-trained model of 1000000 iterations) includes all the files. 
Plz follow the steps of .md file，and the model
will be loaded correctly.

**Comment by nie-lang** [comment]
Modify the version of the skimage library in your condo env to ensure it has ‘measure’ module to calculate psnr/ssim.

**Comment by FXY0117** [comment]
Thank you for your solution

**Comment by FXY0117** [comment]
Excuse me again, is there something wrong with the pretrain reconstruction model, I download it but don't work. It shows that
[TL] Restoring parameters from ./checkpoints/model.ckpt-200000
2021-11-26 14:57:27.330118: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: NewRandomAccessFile failed to Create/Open: ./check
points/model.ckpt-200000.data-00000-of-00001 : 系统找不到指定的文件。
; No such file or directory

Actually, I have moved downloaded model in the checkpoint file.

**Comment by nie-lang** [comment]
> Excuse me again, is there something wrong with the pretrain reconstruction model, I download it but don't work. It shows that [TL] Restoring parameters from ./checkpoints/model.ckpt-200000 2021-11-26 14:57:27.330118: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: NewRandomAccessFile failed to Create/Open: ./check points/model.ckpt-200000.data-00000-of-00001 : 系统找不到指定的文件。 ; No such file or directory
> 
> Actually, I have moved downloaded model in the checkpoint file.

其他测试者（包括我）都没遇到过这个问题。
请仔细检查ImageReconstruction/Codes/chckpoints/文件目录下是否存在预训练模型提供的这4个文件.
如果还是不行，有可能模型已损坏，建议百度云或google drive重新下载。
如果最终实在是不行，按照.md文件的步骤重新训练这一部分吧，性能和提供的预训练模型差距不大的。

**Comment by FXY0117** [comment]
ok, I will check again seriously

**Comment by FXY0117** [comment]
Could you offer me the VGG19 npy files for training in my own dataset, I have failed downloading this files in https://github.com/machrisaa/tensorflow-vgg several times. I can't open the VGG19 NPY website.

**Comment by nie-lang** [comment]
> Could you offer me the VGG19 npy files for training in my own dataset, I have failed downloading this files in https://github.com/machrisaa/tensorflow-vgg several times. I can't open the VGG19 NPY website.

[Baidu Cloud](https://pan.baidu.com/s/1llFq8kn5bCIEnjgjmzUE-w)(Extraction code: 1234) or [Google Drive](https://drive.google.com/drive/folders/1rawASuWGSMzppVoqckKOmAdyxOnI1RzT?usp=sharing)

**Comment by FXY0117** [comment]
Thanks a lot!

**Comment by lxc5720** [comment]
请问，我在Ubuntu环境下在运行inference.py文件时，我已将您发布在百度网盘的预训练好的放在了checkpoints文件夹下，并将constant.py文件下的SNAPSHOT_DIR修改成了绝对路径：
"/media/lxc115720/stduy/python_study/python_deep_lerning/UnsupervisedDeepImageStitching-main/ImageReconstruction/Codes/checkpoints"，但在运行时出现以下错误：

Restored model parameters from /media/lxc115720/stduy/python_study/python_deep_lerning/UnsupervisedDeepImageStitching-main/ImageReconstruction/Codes/checkpoints/model.ckpt-200000
============
i = 0 / 1106
Traceback (most recent call last):
  File "/media/lxc115720/stduy/python_study/python_deep_lerning/UnsupervisedDeepImageStitching-main/ImageReconstruction/Codes/inference.py", line 69, in <module>
    inference_func(snapshot_dir)
  File "/media/lxc115720/stduy/python_study/python_deep_lerning/UnsupervisedDeepImageStitching-main/ImageReconstruction/Codes/inference.py", line 58, in inference_func
    input_clip = np.expand_dims(data_loader.get_image_clips(i), axis=0)
  File "/media/lxc115720/stduy/python_study/python_deep_lerning/UnsupervisedDeepImageStitching-main/ImageReconstruction/Codes/utils.py", line 62, in get_image_clips
    batch.append(np_load_input(image_info_list[2]['frame'][index]))
IndexError: list index out of range
您能给我一点儿建议吗？

**Comment by lxc5720** [comment]
请问，我在Ubuntu环境下在运行inference.py文件时，我已将您发布在百度网盘的预训练好的放在了checkpoints文件夹下，并将constant.py文件下的SNAPSHOT_DIR修改成了绝对路径：
"/media/lxc115720/stduy/python_study/python_deep_lerning/UnsupervisedDeepImageStitching-main/ImageReconstruction/Codes/checkpoints"，但在运行时出现以下错误：

Restored model parameters from /media/lxc115720/stduy/python_study/python_deep_lerning/UnsupervisedDeepImageStitching-main/ImageReconstruction/Codes/checkpoints/model.ckpt-200000
i = 0 / 1106
Traceback (most recent call last):
File "/media/lxc115720/stduy/python_study/python_deep_lerning/UnsupervisedDeepImageStitching-main/ImageReconstruction/Codes/inference.py", line 69, in
inference_func(snapshot_dir)
File "/media/lxc115720/stduy/python_study/python_deep_lerning/UnsupervisedDeepImageStitching-main/ImageReconstruction/Codes/inference.py", line 58, in inference_func
input_clip = np.expand_dims(data_loader.get_image_clips(i), axis=0)
File "/media/lxc115720/stduy/python_study/python_deep_lerning/UnsupervisedDeepImageStitching-main/ImageReconstruction/Codes/utils.py", line 62, in get_image_clips
batch.append(np_load_input(image_info_list[2]['frame'][index]))
IndexError: list index out of range
您能给我一点儿建议吗？

**Comment by ZhangYH-999** [comment]
Excuse me , I have modified the codes in line 71 of ImageAlignment/Codes/utils.py from
`data_name = data.split('/')[-1]`  to  `data_name = data.split('\\')[-1]`
But when I run the 'ImageAlignment/Codes/inference.py', it still occurs the error:

image = np_load_frame(data_info_list[i]['frame'][index], resize_height, resize_width)
IndexError: list index out of range

**Comment by Chimaco37** [comment]
> 

yes it is , the input images of the testing folder should be split to input1/input2 folders, it is not the "/ or \" problem. Hope this be helpful.
![image](https://github.com/nie-lang/UnsupervisedDeepImageStitching/assets/77201421/a0a64967-e69c-4462-9a34-be817009fca6)
