### ISSUE TITLE
testing question

### ISSUE THREAD

**Issue by yjg123456** [nie-lang/UnsupervisedDeepImageStitching#26]
hello， i met this question when i testing ,i couldn't  understand the  reason, could you help me?  thanks.

Traceback (most recent call last):
  File "inference.py", line 105, in <module>
    inference_func(snapshot_dir)
  File "inference.py", line 64, in inference_func
    _, _, _, _, _, warp, _, _, warp_one = sess.run([test_net1_f, test_net2_f, test_net3_f, test_warp2_H1, test_warp2_H2, test_warp2_H3, test_one_warp_H1, test_one_warp_H2, test_one_warp_H3], feed_dict={test_inputs: input_clip})
  File "/home/gfzx/anaconda3/envs/yjgMosaic-Unsupervised/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/gfzx/anaconda3/envs/yjgMosaic-Unsupervised/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 128, 128, 6) for Tensor 'dataset/Placeholder:0', which has shape '(4, 128, 128, 6)'
(yjgMosaic-Unsupervised)

**Comment by nie-lang** [comment]
It seems there's something wrong with the  "batch_size". You load the data that has the shape (1, 128, 128, 6), but the predefined tensor has the shape (4, 128, 128, 6).
![image](https://user-images.githubusercontent.com/54256137/160269482-6bd92e66-e170-4664-9167-2c56516c8838.png)
Please check the TEST_BATCH_SIZE.

**Comment by yjg123456** [comment]
> It seems there's something wrong with the "batch_size". You load the data that has the shape (1, 128, 128, 6), but the predefined tensor has the shape (4, 128, 128, 6). ![image](https://user-images.githubusercontent.com/54256137/160269482-6bd92e66-e170-4664-9167-2c56516c8838.png) Please check the TEST_BATCH_SIZE.

thanks for your reply ,but  the batch_size is 4,  i don't  change it !
this is output  in  running process:
 
test inputs = Tensor("dataset/Placeholder:0", shape=(4, 128, 128, 6), dtype=float32)

**Comment by nie-lang** [comment]
> > It seems there's something wrong with the "batch_size". You load the data that has the shape (1, 128, 128, 6), but the predefined tensor has the shape (4, 128, 128, 6). ![image](https://user-images.githubusercontent.com/54256137/160269482-6bd92e66-e170-4664-9167-2c56516c8838.png) Please check the TEST_BATCH_SIZE.
> 
> thanks for your reply ,but the batch_size is 4, i don't change it ! this is output in running process:
> 
> test inputs = Tensor("dataset/Placeholder:0", shape=(4, 128, 128, 6), dtype=float32)

The batch size is defined in constant.py where bs is 4 for training and 1 for testing. Please check your code carefully. Maybe printing the value of batch_size can be helpful.

**Comment by yjg123456** [comment]
> > > It seems there's something wrong with the "batch_size". You load the data that has the shape (1, 128, 128, 6), but the predefined tensor has the shape (4, 128, 128, 6). ![image](https://user-images.githubusercontent.com/54256137/160269482-6bd92e66-e170-4664-9167-2c56516c8838.png) Please check the TEST_BATCH_SIZE.
> > 
> > 
> > thanks for your reply ,but the batch_size is 4, i don't change it ! this is output in running process:
> > test inputs = Tensor("dataset/Placeholder:0", shape=(4, 128, 128, 6), dtype=float32)
> 
> The batch size is defined in constant.py where bs is 4 for training and 1 for testing. Please check your code carefully. Maybe printing the value of batch_size can be helpful.

yeah, i get it .thanks again!
but i met a new question now , the psnr is nan.
===================Results Analysis==================
top 30% nan
top 30~60% nan
top 60~100% nan
average psnr: nan
top 30% nan
top 30~60% nan
top 60~100% nan
average ssim: nan
(yjgMosaic-Unsupervised)

**Comment by nie-lang** [comment]
> > > > It seems there's something wrong with the "batch_size". You load the data that has the shape (1, 128, 128, 6), but the predefined tensor has the shape (4, 128, 128, 6). ![image](https://user-images.githubusercontent.com/54256137/160269482-6bd92e66-e170-4664-9167-2c56516c8838.png) Please check the TEST_BATCH_SIZE.
> > > 
> > > 
> > > thanks for your reply ,but the batch_size is 4, i don't change it ! this is output in running process:
> > > test inputs = Tensor("dataset/Placeholder:0", shape=(4, 128, 128, 6), dtype=float32)
> > 
> > 
> > The batch size is defined in constant.py where bs is 4 for training and 1 for testing. Please check your code carefully. Maybe printing the value of batch_size can be helpful.
> 
> yeah, i get it .thanks again! but i met a new question now , the psnr is nan. ===================Results Analysis================== top 30% nan top 30~60% nan top 60~100% nan average psnr: nan top 30% nan top 30~60% nan top 60~100% nan average ssim: nan (yjgMosaic-Unsupervised)

Check the output of the network by running output_inference.py.
