### ISSUE TITLE
inference.py  list index out of range

### ISSUE THREAD

**Issue by monkeycc** [nie-lang/UnsupervisedDeepImageStitching#55]
```
python inference.py
D:\anaconda3ok\envs\DeepImageStitching\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\anaconda3ok\envs\DeepImageStitching\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\anaconda3ok\envs\DeepImageStitching\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\anaconda3ok\envs\DeepImageStitching\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\anaconda3ok\envs\DeepImageStitching\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\anaconda3ok\envs\DeepImageStitching\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
test inputs = Tensor("dataset/Placeholder:0", shape=(1, 128, 128, 6), dtype=float32)
testing = generator
WARNING:tensorflow:From D:\anaconda3ok\envs\DeepImageStitching\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From D:\anaconda3ok\envs\DeepImageStitching\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From D:\anaconda3ok\envs\DeepImageStitching\lib\site-packages\tensorflow\python\keras\layers\core.py:143: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
--Shape of A_mat: [1, 8, 8]
--shape of b: [1, 8, 1]
--shape of H_8el Tensor("generator/model/MatrixSolve:0", shape=(1, 8, 1), dtype=float32)
--Shape of A_mat: [1, 8, 8]
--shape of b: [1, 8, 1]
--shape of H_8el Tensor("generator/model/MatrixSolve_1:0", shape=(1, 8, 1), dtype=float32)
--Shape of A_mat: [1, 8, 8]
--shape of b: [1, 8, 1]
--shape of H_8el Tensor("generator/MatrixSolve:0", shape=(1, 8, 1), dtype=float32)
--Shape of A_mat: [1, 8, 8]
--shape of b: [1, 8, 1]
--shape of H_8el Tensor("generator/MatrixSolve_1:0", shape=(1, 8, 1), dtype=float32)
--Shape of A_mat: [1, 8, 8]
--shape of b: [1, 8, 1]
--shape of H_8el Tensor("generator/MatrixSolve_2:0", shape=(1, 8, 1), dtype=float32)
2022-11-02 16:27:26.594633: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
odict_keys([])
Init global successfully!
============
D:/0SDXX/UnsupervisedDeepImageStitching-main/checkpoints_homo/model.ckpt-1000000
WARNING:tensorflow:From D:\anaconda3ok\envs\DeepImageStitching\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restored model parameters from D:/0SDXX/UnsupervisedDeepImageStitching-main/checkpoints_homo/model.ckpt-1000000
============
Traceback (most recent call last):
  File "inference.py", line 105, in <module>
    inference_func(snapshot_dir)
  File "inference.py", line 61, in inference_func
    input_clip = np.expand_dims(data_loader.get_data_clips(i, 128, 128), axis=0)
  File "D:\0SDXX\UnsupervisedDeepImageStitching-main\ImageAlignment\Codes\utils.py", line 86, in get_data_clips
    image = np_load_frame(data_info_list[i]['frame'][index], resize_height, resize_width)
IndexError: list index out of range
```

**Comment by jeffabc1997** [comment]
You could check whether your input images are on the right path. The data folder can be modified in constant.py.

**Comment by zhaomeinie** [comment]
I had the same problem. If you are windows os user, you can try to change '/' to '\\' in 'line 71 of ImageAlignment/Codes/utils.py' and 'line 48 of ImageReconstruction/Codes/utils.py'. Notice, it's "\\", not "\\\\".
