### ISSUE TITLE
ImageAlignment 加载COCO预训练权重报错！

### ISSUE THREAD

**Issue by Williamwsk** [nie-lang/UnsupervisedDeepImageStitching#9]
您好，ImageAlignment网络在COCO上训练完后，加载在COCO上的预训练权重，报如下错误
Restored model parameters from ./checkpoints_homo/model.ckpt-600000
============starting training===========
Training generator...
2021-11-12 07:54:43.722094: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2021-11-12 07:54:44.270828: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2021-11-12 07:54:46.183286: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2021-11-12 07:54:46.377568: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2021-11-12 07:54:57.017388: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2021-11-12 07:55:07.398546: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-11-12 07:55:07.400147: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-11-12 07:55:07.403547: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-11-12 07:55:07.405338: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node generator/model/feature_extract/conv_block1/conv1/Conv2D}}]]
         [[{{node loss/add_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_H.py", line 133, in <module>
    _, _g_lr, _step, _lp_loss, _g_loss, _summaries = sess.run([g_train_op, g_lrate, g_step, lp_loss,  g_loss, summary_op])
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node generator/model/feature_extract/conv_block1/conv1/Conv2D (defined at /root/xdf/UnsupervisedDeepImageStitching/ImageAlignment/Codes/H_model.py:65) ]]
         [[node loss/add_1 (defined at train_H.py:60) ]]

Caused by op 'generator/model/feature_extract/conv_block1/conv1/Conv2D', defined at:
  File "train_H.py", line 51, in <module>
    train_net1_f, train_net2_f, train_net3_f, train_warp2_H1, train_warp2_H2, train_warp2_H3, train_one_warp_H1, train_one_warp_H2, train_one_warp_H3 = H_estimator(train_inputs_aug, train_inputs, True)
  File "/root/xdf/UnsupervisedDeepImageStitching/ImageAlignment/Codes/models.py", line 9, in H_estimator
    return H_model.H_model(inputs_aug, inputs, is_training)
  File "/root/xdf/UnsupervisedDeepImageStitching/ImageAlignment/Codes/H_model.py", line 12, in H_model
    net1_f, net2_f, net3_f = build_model(inputs_aug, is_training)
  File "/root/xdf/UnsupervisedDeepImageStitching/ImageAlignment/Codes/H_model.py", line 61, in build_model
    net1_f, net2_f, net3_f = _H_model(input1, input2, is_training)
  File "/root/xdf/UnsupervisedDeepImageStitching/ImageAlignment/Codes/H_model.py", line 117, in _H_model
    feature1 = feature_extractor(input1)
  File "/root/xdf/UnsupervisedDeepImageStitching/ImageAlignment/Codes/H_model.py", line 73, in feature_extractor
    conv1 = _conv_block(image_tf, ([64, 64]), (3, 3), (1, 1))
  File "/root/xdf/UnsupervisedDeepImageStitching/ImageAlignment/Codes/H_model.py", line 65, in _conv_block
    conv1 = conv2d(inputs=x, num_outputs=num_out_layers[0], kernel_size=kernel_sizes[0], activation_fn=tf.nn.relu, scope='conv1')
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1155, in convolution2d
    conv_dims=2)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1058, in convolution
    outputs = layer.apply(inputs)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 208, in __call__
    name=self.name)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/root/miniconda3/envs/ScanPen/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node generator/model/feature_extract/conv_block1/conv1/Conv2D (defined at /root/xdf/UnsupervisedDeepImageStitching/ImageAlignment/Codes/H_model.py:65) ]]

不加载COCO上的预训练就OK，一加载就报错

**Comment by nie-lang** [comment]
你好，这个问题我从来没遇到过。我刚刚在自己环境下测试了一下，是能够正常finetune的。

更大的可能是cuda+cuDNN+TensorFlow的版本匹配不一致，尤其是TensorFlow的版本过高了。

这里我分享一下我当时的训练环境：（GPU RTX 2080Ti）CUDA10，CUDNN7.6.5,  tensorflow-gpu-1.13.1

但直接train就ok，finetune就报错，这非常奇怪。也许还可以检查一下数据集有没有正确读入。

**Comment by nie-lang** [comment]
也可以把UDIS-D数据集先换成COCO，相当于COCO上预训练后，继续在COCO上finetune。如果这能work的话，说明是数据集没有正确读入，比如路径不对等。不能work的话，多半是环境问题

**Comment by Williamwsk** [comment]
> 你好，这个问题我从来没遇到过。我刚刚在自己环境下测试了一下，是能够正常finetune的。
> 
> 更大的可能是cuda+cuDNN+TensorFlow的版本匹配不一致，尤其是TensorFlow的版本过高了。
> 
> 这里我分享一下我当时的训练环境：（GPU RTX 2080Ti）CUDA10，CUDNN7.6.5, tensorflow-gpu-1.13.1
> 
> 但直接train就ok，finetune就报错，这非常奇怪。也许还可以检查一下数据集有没有正确读入。

这是我的Docker里面的环境，也都是按您的版本号下载的
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
python                    3.7.11               h12debd9_0  
tensorboard               1.13.1           py37hf484d3e_0  
tensorflow                1.13.1          gpu_py37hc158e3b_0  
tensorflow-base           1.13.1          gpu_py37h8d69cac_0  
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.13.1               h0d30ee6_0

**Comment by Williamwsk** [comment]
> 也可以把UDIS-D数据集先换成COCO，相当于COCO上预训练后，继续在COCO上finetune。如果这能work的话，说明是数据集没有正确读入，比如路径不对等。不能work的话，多半是环境问题

我把UDIS-D数据集换成COCO，在COCO上finetune，也还是报上面那个错，环境也都没啥问题，从头训练就没问题，一旦加载预训练权重就不行了

**Comment by nie-lang** [comment]
> > 也可以把UDIS-D数据集先换成COCO，相当于COCO上预训练后，继续在COCO上finetune。如果这能work的话，说明是数据集没有正确读入，比如路径不对等。不能work的话，多半是环境问题
> 
> 我把UDIS-D数据集换成COCO，在COCO上finetune，也还是报上面那个错，环境也都没啥问题，从头训练就没问题，一旦加载预训练权重就不行了

“Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR”，我感觉还是环境的问题。
建议试试直接在cpu上跑一下finetune，cpu能跑的话说明代码模型数据都没问题，只是环境出了点问题。相同的环境不同的显卡有时候也可能会出问题（虽然很少发生）

**Comment by Williamwsk** [comment]
> > > 也可以把UDIS-D数据集先换成COCO，相当于COCO上预训练后，继续在COCO上finetune。如果这能work的话，说明是数据集没有正确读入，比如路径不对等。不能work的话，多半是环境问题
> > 
> > 
> > 我把UDIS-D数据集换成COCO，在COCO上finetune，也还是报上面那个错，环境也都没啥问题，从头训练就没问题，一旦加载预训练权重就不行了
> 
> “Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR”，我感觉还是环境的问题。 建议试试直接在cpu上跑一下finetune，cpu能跑的话说明代码模型数据都没问题，只是环境出了点问题。相同的环境不同的显卡有时候也可能会出问题（虽然很少发生）

嗯嗯，应该是cudnn环境配置的问题，我用CPU可以训练。另外您方便的话可以提供一份代码的docker训练环境吗？
